In [1]:
import numpy
import pandas

In [2]:
with open('./testing wellek\'s test.csv') as infile:
    data = pandas.read_csv(infile, delimiter = '\t')

In [3]:
y = data.iloc[0:10,4].values
x = data.iloc[14:24,4].values

m = len(x)
n = len(y)
x,y,m,n

wxy = 0
for i in range(m):
    for j in range(n):
        diff = (x[i] - y[j])
        # add to ŷ (wxy in mawi.R)
        if diff > 0:
            wxy += 1
wxy = wxy/(m*n)
print('wxy', wxy)

pihxxy = 0
for xi1 in range(m - 1):
    for xi2 in range(xi1 + 1, m):
        for xj in range(n):
            # 1st difference
            diff1 = (x[xi1] - y[xj])
            # 2nd difference
            diff2 = (x[xi2] - y[xj])
            # add to yFGG (pihxxy in mawi.R)
            if diff1 > 0 and diff2 > 0:
                pihxxy += 1
pihxxy = (pihxxy * 2) / (m * (m - 1) * n)
pihxxy

pihxyy = 0
for xi in range(m):
    for xj1 in range(n - 1):
        for xj2 in range(xj1 + 1, n):
            # 1st difference
            diff1 = (x[xi] - y[xj1])
            # 2nd difference
            diff2 = (x[xi] - y[xj2])
            # add to yFGG (pihxxy in mawi.R)
            if diff1 > 0 and diff2 > 0:
                pihxyy += 1
pihxyy = (pihxyy * 2) / (n * (n - 1) * m)
pihxyy

sigmah = wxy - (wxy**2)*(m + n - 1) + pihxxy*(m - 1) + pihxyy*(n - 1)
sigmah = sigmah/(m*n)
sigmah = sigmah**.5
sigmah

eps1_ = .3129 # Wellek's paper
eps2_ = .2661 # Wellek's paper
eqctr = 0.5 + (eps2_ - eps1_)/2
eqleng = eps1_ + eps2_
phi = (eqleng/2/sigmah)**2

phi**.5
abs((wxy - eqctr)/(sigmah))

from scipy.stats import ncx2
ncx2.ppf(.05, 1, phi)
ncx2.ppf(.05, 1, 2.5781**2)

wxy 0.67


0.8749482877661686

In [4]:
x = data.iloc[0:10,4].values
y = data.iloc[14:24,4].values

m = len(x)
n = len(y)
x,y,m,n

wxy = 0
for i in range(m):
    for j in range(n):
        diff = (x[i] - y[j])
        # add to ŷ (wxy in mawi.R)
        wxy += numpy.heaviside(diff, 0)
wxy = wxy/(m*n)
print('wxy', wxy)

pihxxy = 0
for xi1 in range(m - 1):
    for xi2 in range(xi1 + 1, m):
        for xj in range(n):
            # 1st difference
            diff1 = (x[xi1] - y[xj])
            # 2nd difference
            diff2 = (x[xi2] - y[xj])
            # add to yFGG (pihxxy in mawi.R)
            pihxxy += numpy.heaviside(diff1, 0) * numpy.heaviside(diff2, 0)
pihxxy = (pihxxy * 2) / (m * (m - 1) * n)
print('pihxxy', pihxxy)

pihxyy = 0
for xi in range(m):
    for xj1 in range(n - 1):
        for xj2 in range(xj1 + 1, n):
            # 1st difference
            diff1 = (x[xi] - y[xj1])
            # 2nd difference
            diff2 = (x[xi] - y[xj2])
            # add to yFGG (pihxxy in mawi.R)
            pihxyy += numpy.heaviside(diff1, 0) * numpy.heaviside(diff2, 0)
pihxyy = (pihxyy * 2) / (n * (n - 1) * m)
print('pihxyy', pihxyy)

sigmah = wxy - (wxy**2)*(m + n - 1) + pihxxy*(m - 1) + pihxyy*(n - 1)
sigmah = sigmah/(m*n)
sigmah = sigmah**.5
print('sigmah', sigmah)

eps1_ = .3129 # Wellek's paper
eps2_ = .2661 # Wellek's paper
eqctr = 0.5 + (eps2_ - eps1_)/2
eqleng = eps1_ + eps2_
phi = (eqleng/2/sigmah)**2
print('phi', phi)

# phi**.5
print('z', abs((wxy - eqctr)/(sigmah)))

from scipy.stats import ncx2
ncx2.ppf(.05, 1, phi)
# ncx2.ppf(.05, 1, 2.5781**2)

wxy 0.33
pihxxy 0.19111111111111112
pihxyy 0.14222222222222222
sigmah 0.11228980363327741
phi 6.646859386152747
z 1.305550417371597


0.8750410377010782

In [5]:
for val, dat in enumerate(x):
    with open('./x_sims_' + str(val) + '.txt', 'w') as outfile:
        outfile.write('#\n,#\n"[T]","prot"\n1.,' + str(dat) + '\n2.,' + str(dat))

In [6]:
for val, dat in enumerate(y):
    with open('./y_data_' + str(val) + '.txt', 'w') as outfile:
        outfile.write('"[T]","prot"\n1.,' + str(dat) + '\n2.,' + str(dat))

In [7]:
x

array([-0.05461,  0.05398,  0.13695,  0.02643, -0.09486, -0.09128,
       -0.34926,  0.04718,  0.0529 , -0.27221])

In [8]:
y

array([ 0.10725,  0.35161, -0.18893, -0.03187,  0.02636,  0.14799,
        0.18748,  0.06717, -0.18813,  0.00991])

In [13]:
numpy.random.normal(0, 1, 40)

array([-0.16153141,  0.51689718,  0.82485348,  1.88079073,  0.14596686,
        0.75052658, -0.30461629,  0.44423477,  1.21759282,  0.83976447,
        0.14441561,  0.60657143,  0.29029759, -0.35331668, -0.98668225,
       -0.73234587,  2.53805364,  0.07150216, -0.95770403,  1.37884418,
        0.26872801,  0.05941533, -0.21610691, -0.04690926, -0.06496887,
        0.48821366,  0.09426828,  0.54059404, -1.09826617, -1.13315112,
       -0.29670306,  0.81590551,  0.4075118 ,  0.09937079, -1.50085668,
       -1.13253336,  0.7162246 , -0.69784134,  0.30295901, -1.45927346])

In [14]:
numpy.random.normal(0, 1, 40)

array([-1.05406769, -2.60828722,  0.49224267,  1.60482672, -0.75918251,
       -0.2755435 ,  0.36049076, -0.31875002,  0.1554656 , -0.51934305,
       -1.13729509, -0.43088847, -0.5343316 , -0.54159193, -1.24268563,
        0.81660478,  0.11672374,  0.93622193, -1.11111526, -2.00100046,
        0.38924143,  1.77103738,  1.49857153, -0.73455776,  0.77534645,
       -0.0481238 , -0.80264852, -0.20574817,  0.22817936, -0.57795961,
       -2.19567051, -1.03149542,  1.41021596,  1.32868154, -2.30569814,
        0.29320924,  0.20289409, -0.43415581,  1.65487862,  1.55974042])